export const defaultUserLayout: Layer[] = [
  {
    name: "base",
    legends: [
      "esc",
      "w",
      "l",
      "y",
      "p",
      "k",
      "del",
      "c",
      "r",
      "s",
      "t",
      "b",
      "raycast",
      "q",
      "j",
      "v",
      "d",
      "g",
      null,
      "nav",
      "space",
      "z",
      "x",
      "o",
      "u",
      "alt",
      "lang",
      "f",
      "e",
      "i",
      "i",
      "a",
      null,
      "m",
      "h",
      ".",
      ",",
      "ctr",
      null,
      "osm shift",
      "sym\n/\nnum",
    ],
    order: 0,
    specialKeys: [
      { index: 0, category: 1 },
      { index: 37, category: 2 },
      { index: 25, category: 2 },
      { index: 26, category: 1 },
      { index: 6, category: 1 },
      { index: 12, category: 2 },
      { index: 40, category: 2 },
      { index: 39, category: 2 },
      { index: 19, category: 2 },
      { index: 20, category: 1 },
    ],
  },
  {
    name: "symbols",
    legends: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "5",
      "4",
      "3",
      "1",
      "9",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "8",
      "0",
      "2",
      "4",
      "6",
    ],
    order: 1,
  },
  {
    name: "symbols",
    legends: ["", "]", ">", "}", ")", "", "", "[", "<", "{", "("],
    order: 2,
  },
];
