export const defaultUserLayout: Layer[] = [
  {
    name: "base",
    legends: [
      "esc",
      "w",
      "l",
      "y",
      "p",
      "k",
      "del",
      "c",
      "r",
      "s",
      "t",
      "b",
      "raycast",
      "q",
      "j",
      "v",
      "d",
      "g",
      null,
      "nav",
      "space",
      "z",
      "x",
      "o",
      "u",
      "alt",
      "lang",
      "f",
      "e",
      "i",
      "i",
      "a",
      null,
      "m",
      "h",
      ".",
      ",",
      "ctr",
      null,
      "osm shift",
      "sym\n/\nnum",
    ],
    order: 0,
    specialKeys: [
      { index: 0, category: 1 },
      { index: 37, category: 2 },
      { index: 25, category: 2 },
      { index: 26, category: 1 },
      { index: 6, category: 1 },
      { index: 12, category: 2 },
      { index: 40, category: 2 },
      { index: 39, category: 2 },
      { index: 19, category: 2 },
      { index: 20, category: 1 },
    ],
  },
  {
    name: "combo",
    legends: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "tab",
      "tab",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "enter",
      "enter",
    ],
    order: 3,
    specialKeys: [
      { index: 22, category: 1 },
      { index: 23, category: 1 },
      { index: 35, category: 1 },
      { index: 34, category: 1 },
    ],
  },
  {
    name: "home row mods",
    legends: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "option",
      "ctrl",
      "cmd",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "cmd",
      "ctrl",
      "option",
    ],
    order: 5,
    specialKeys: [
      { index: 8, category: 2 },
      { index: 9, category: 2 },
      { index: 10, category: 2 },
      { index: 30, category: 2 },
      { index: 29, category: 2 },
      { index: 28, category: 2 },
    ],
  },
  {
    name: "symbols",
    legends: [
      "",
      "]",
      ">",
      "}",
      ")",
      "&",
      "",
      "[",
      "<",
      "{",
      "(",
      "=",
      null,
      "",
      "*",
      "/",
      "-",
      "+",
      null,
      null,
      null,
      "|",
      '"',
      "'",
      "`",
      null,
      null,
      "@",
      ";",
      ":",
      "?",
      "!",
      null,
      "$",
      "#",
      "%",
      "_",
      null,
      null,
      null,
      "osm",
    ],
    order: 2,
    specialKeys: [{ index: 40, category: 2 }],
  },
  {
    name: "numbers",
    legends: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "5",
      "4",
      "3",
      "1",
      "9",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "8",
      "0",
      "2",
      "4",
      "6",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "hold",
    ],
    order: 1,
    specialKeys: [{ index: 40, category: 2 }],
  },

  {
    name: "navigation",
    legends: [
      null,
      null,
      "select all",
      "chrome\ndev\ntools",
      "find",
      null,
      null,
      null,
      "save",
      "vs \ncode\naction",
      "right\nmouse\nclick",
      null,
      null,
      null,
      "cut",
      "copy",
      "paste",
      null,
      null,
      null,
      null,
      null,
      "home",
      "up",
      "end",
      null,
      null,
      null,
      "left",
      "down",
      "center",
    ],
    order: 4,
    specialKeys: [
      { index: 23, category: 1 },
      { index: 29, category: 1 },
      { index: 22, category: 1 },
      { index: 28, category: 1 },
      { index: 24, category: 1 },
      { index: 30, category: 1 },
      { index: 10, category: 2 },
      { index: 9, category: 2 },
      { index: 2, category: 2 },
      { index: 8, category: 2 },
      { index: 3, category: 2 },
      { index: 4, category: 2 },
      { index: 16, category: 2 },
      { index: 15, category: 2 },
      { index: 14, category: 2 },
    ],
  },
];
